export const doctors = [
  {
    id: 1,
    name: "Dr. Marcus Thorne",
    specialty: "Cardiology",
    rating: "4.9",
    reviews: "128",
    location: "MedCenter, SF",
    experience: "15+ Yrs Exp",
    availableNow: true,
    price: "$180.00",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80",
    about: "Dr. Marcus Thorne is a board-certified cardiologist specializing in preventive cardiology and heart failure. He has over 15 years of experience treating complex cardiovascular conditions."
  },
  {
    id: 2,
    name: "Dr. Elena Rodriguez",
    specialty: "Pediatrics",
    rating: "5.0",
    reviews: "242",
    location: "Children's Health, Austin",
    experience: "8+ Yrs Exp",
    availableNow: true,
    price: "$145.00",
    image: "https://images.unsplash.com/photo-1594824436998-d467946927d7?w=400&q=80",
    about: "Dr. Elena Rodriguez is dedicated to providing comprehensive pediatric care from newborns to adolescents. Her gentle approach ensures children feel comfortable and safe during visits."
  },
  {
    id: 3,
    name: "Dr. James Wilson",
    specialty: "Dermatology",
    rating: "4.8",
    reviews: "86",
    location: "Skin Institute, NYC",
    experience: "12+ Yrs Exp",
    availableNow: true,
    price: "$210.00",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&q=80",
    about: "Dr. James Wilson is a renowned dermatologist focusing on medical, surgical, and cosmetic dermatology. He is highly skilled in treating a wide array of skin conditions and developing personalized skincare regimens."
  },
  {
    id: 4,
    name: "Dr. Sarah Chen",
    specialty: "General Practice",
    rating: "4.9",
    reviews: "156",
    location: "Mount Sinai, NY",
    experience: "10+ Yrs Exp",
    availableNow: false,
    price: "$150.00",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80",
    about: "Dr. Sarah Chen provides comprehensive primary care to patients of all ages, focusing on preventive medicine and chronic disease management."
  },
  {
    id: 5,
    name: "Dr. Michael Chang",
    specialty: "Cardiology",
    rating: "4.7",
    reviews: "98",
    location: "Heart Care, Chicago",
    experience: "14+ Yrs Exp",
    availableNow: true,
    price: "$220.00",
    image: "https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=400&q=80",
    about: "Dr. Michael Chang is an expert in treating heart arrhythmias and coronary artery disease. He is dedicated to helping patients regain their heart health."
  },
  {
    id: 6,
    name: "Dr. Emily Taylor",
    specialty: "General Practice",
    rating: "5.0",
    reviews: "312",
    location: "Wellness Clinic, Seattle",
    experience: "9+ Yrs Exp",
    availableNow: true,
    price: "$160.00",
    image: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&q=80",
    about: "Dr. Emily Taylor offers compassionate primary care, focusing on holistic health, nutrition counseling, and stress management."
  },
  {
    id: 7,
    name: "Dr. David Kim",
    specialty: "Dermatology",
    rating: "4.8",
    reviews: "124",
    location: "Clear Skin Clinic, SF",
    experience: "7+ Yrs Exp",
    availableNow: true,
    price: "$190.00",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80",
    about: "Dr. David Kim specializes in acne treatment, skin cancer screening, and anti-aging treatments. He uses the latest technologies for optimal results."
  },
  {
    id: 8,
    name: "Dr. Lisa Patel",
    specialty: "Pediatrics",
    rating: "4.9",
    reviews: "189",
    location: "Kids Care, NYC",
    experience: "11+ Yrs Exp",
    availableNow: false,
    price: "$155.00",
    image: "https://images.unsplash.com/photo-1594824436998-d467946927d7?w=400&q=80",
    about: "Dr. Lisa Patel provides excellent pediatric care, from routine checkups and immunizations to managing complex childhood illnesses."
  }
];
